---
- name: Reload Nginx
  service:
    name: nginx
    state: reloaded

- name: Restart EpicBook app
  command: pm2 restart epicbook --update-env
  args:
    chdir: "{{ app_dest }}"
  become: true
  become_user: "{{ app_user }}"
  environment:
    PM2_HOME: "{{ pm2_home }}"
    HOME: "{{ app_home }}"